/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ApplicationSubmittedRouteImport } from './routes/application-submitted'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BookRouteImport } from './routes/book'
import { Route as ComingSoonRouteImport } from './routes/coming-soon'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as BlogsIndexRouteImport } from './routes/blogs.index'
import { Route as BlogsSlugRouteImport } from './routes/blogs.$slug'
import { Route as CareersIndexRouteImport } from './routes/careers.index'
import { Route as CareersSlugRouteImport } from './routes/careers.$slug'
import { Route as CaseStudiesIndexRouteImport } from './routes/case-studies.index'
import { Route as CaseStudiesSlugRouteImport } from './routes/case-studies.$slug'
import { Route as IndustriesIndexRouteImport } from './routes/industries.index'
import { Route as IndustriesSlugRouteImport } from './routes/industries.$slug'
import { Route as PortfolioIndexRouteImport } from './routes/portfolio.index'
import { Route as PortfolioSlugRouteImport } from './routes/portfolio.$slug'
import { Route as ResourcesIndexRouteImport } from './routes/resources.index'
import { Route as ResourcesSlugRouteImport } from './routes/resources.$slug'
import { Route as ServiceSlugRouteImport } from './routes/service.$slug'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as ToolsIndexRouteImport } from './routes/tools.index'
import { Route as ToolsSlugRouteImport } from './routes/tools.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminBookingsRouteImport } from './routes/_authenticated/admin.bookings'
import { Route as AuthenticatedAdminDocumentsRouteImport } from './routes/_authenticated/admin.documents'
import { Route as AuthenticatedAdminFollowupsRouteImport } from './routes/_authenticated/admin.followups'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated/admin.notifications'
import { Route as AuthenticatedAdminTasksRouteImport } from './routes/_authenticated/admin.tasks'
import { Route as AuthenticatedAdminTeamRouteImport } from './routes/_authenticated/admin.team'
import { Route as ApiDownloadsNameRouteImport } from './routes/api/downloads.$name'
import { Route as AuthenticatedAdminCustomersIndexRouteImport } from './routes/_authenticated/admin.customers.index'
import { Route as AuthenticatedAdminCustomersIdRouteImport } from './routes/_authenticated/admin.customers.$id'
import { Route as AuthenticatedAdminEnquiriesIndexRouteImport } from './routes/_authenticated/admin.enquiries.index'
import { Route as AuthenticatedAdminEnquiriesIdRouteImport } from './routes/_authenticated/admin.enquiries.$id'
import { Route as AuthenticatedAdminWebsiteIndexRouteImport } from './routes/_authenticated/admin.website.index'
import { Route as AuthenticatedAdminWebsiteApplicationsRouteImport } from './routes/_authenticated/admin.website.applications'
import { Route as AuthenticatedAdminWebsiteFinancialRouteImport } from './routes/_authenticated/admin.website.financial'
import { Route as AuthenticatedAdminWebsiteMediaRouteImport } from './routes/_authenticated/admin.website.media'
import { Route as AuthenticatedAdminWebsiteSettingsRouteImport } from './routes/_authenticated/admin.website.settings'
import { Route as ApiPublicMediaIdRouteImport } from './routes/api/public/media.$id'
import { Route as AuthenticatedAdminWebsiteModuleIndexRouteImport } from './routes/_authenticated/admin.website.$module.index'
import { Route as AuthenticatedAdminWebsiteModuleIdRouteImport } from './routes/_authenticated/admin.website.$module.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationSubmittedRoute = ApplicationSubmittedRouteImport.update({
  id: '/application-submitted',
  path: '/application-submitted',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const ComingSoonRoute = ComingSoonRouteImport.update({
  id: '/coming-soon',
  path: '/coming-soon',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsSlugRoute = BlogsSlugRouteImport.update({
  id: '/blogs/$slug',
  path: '/blogs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersIndexRoute = CareersIndexRouteImport.update({
  id: '/careers/',
  path: '/careers/',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersSlugRoute = CareersSlugRouteImport.update({
  id: '/careers/$slug',
  path: '/careers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesIndexRoute = CaseStudiesIndexRouteImport.update({
  id: '/case-studies/',
  path: '/case-studies/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesSlugRoute = CaseStudiesSlugRouteImport.update({
  id: '/case-studies/$slug',
  path: '/case-studies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesIndexRoute = IndustriesIndexRouteImport.update({
  id: '/industries/',
  path: '/industries/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesSlugRoute = IndustriesSlugRouteImport.update({
  id: '/industries/$slug',
  path: '/industries/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({
  id: '/portfolio/',
  path: '/portfolio/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioSlugRoute = PortfolioSlugRouteImport.update({
  id: '/portfolio/$slug',
  path: '/portfolio/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesSlugRoute = ResourcesSlugRouteImport.update({
  id: '/resources/$slug',
  path: '/resources/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceSlugRoute = ServiceSlugRouteImport.update({
  id: '/service/$slug',
  path: '/service/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSlugRoute = ToolsSlugRouteImport.update({
  id: '/tools/$slug',
  path: '/tools/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminBookingsRoute =
  AuthenticatedAdminBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDocumentsRoute =
  AuthenticatedAdminDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFollowupsRoute =
  AuthenticatedAdminFollowupsRouteImport.update({
    id: '/followups',
    path: '/followups',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTasksRoute = AuthenticatedAdminTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTeamRoute = AuthenticatedAdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiDownloadsNameRoute = ApiDownloadsNameRouteImport.update({
  id: '/api/downloads/$name',
  path: '/api/downloads/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminCustomersIndexRoute =
  AuthenticatedAdminCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCustomersIdRoute =
  AuthenticatedAdminCustomersIdRouteImport.update({
    id: '/customers/$id',
    path: '/customers/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEnquiriesIndexRoute =
  AuthenticatedAdminEnquiriesIndexRouteImport.update({
    id: '/enquiries/',
    path: '/enquiries/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEnquiriesIdRoute =
  AuthenticatedAdminEnquiriesIdRouteImport.update({
    id: '/enquiries/$id',
    path: '/enquiries/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminWebsiteIndexRoute =
  AuthenticatedAdminWebsiteIndexRouteImport.update({
    id: '/website/',
    path: '/website/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminWebsiteApplicationsRoute =
  AuthenticatedAdminWebsiteApplicationsRouteImport.update({
    id: '/website/applications',
    path: '/website/applications',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminWebsiteFinancialRoute =
  AuthenticatedAdminWebsiteFinancialRouteImport.update({
    id: '/website/financial',
    path: '/website/financial',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminWebsiteMediaRoute =
  AuthenticatedAdminWebsiteMediaRouteImport.update({
    id: '/website/media',
    path: '/website/media',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminWebsiteSettingsRoute =
  AuthenticatedAdminWebsiteSettingsRouteImport.update({
    id: '/website/settings',
    path: '/website/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicMediaIdRoute = ApiPublicMediaIdRouteImport.update({
  id: '/api/public/media/$id',
  path: '/api/public/media/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminWebsiteModuleIndexRoute =
  AuthenticatedAdminWebsiteModuleIndexRouteImport.update({
    id: '/website/$module/',
    path: '/website/$module/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminWebsiteModuleIdRoute =
  AuthenticatedAdminWebsiteModuleIdRouteImport.update({
    id: '/website/$module/$id',
    path: '/website/$module/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/application-submitted': typeof ApplicationSubmittedRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/coming-soon': typeof ComingSoonRoute
  '/contact': typeof ContactRoute
  '/downloads': typeof DownloadsRoute
  '/maintenance': typeof MaintenanceRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/blogs/$slug': typeof BlogsSlugRoute
  '/careers/$slug': typeof CareersSlugRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/service/$slug': typeof ServiceSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/blogs/': typeof BlogsIndexRoute
  '/careers/': typeof CareersIndexRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
  '/industries/': typeof IndustriesIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/admin/followups': typeof AuthenticatedAdminFollowupsRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/tasks': typeof AuthenticatedAdminTasksRoute
  '/admin/team': typeof AuthenticatedAdminTeamRoute
  '/api/downloads/$name': typeof ApiDownloadsNameRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/customers/$id': typeof AuthenticatedAdminCustomersIdRoute
  '/admin/enquiries/$id': typeof AuthenticatedAdminEnquiriesIdRoute
  '/admin/website/applications': typeof AuthenticatedAdminWebsiteApplicationsRoute
  '/admin/website/financial': typeof AuthenticatedAdminWebsiteFinancialRoute
  '/admin/website/media': typeof AuthenticatedAdminWebsiteMediaRoute
  '/admin/website/settings': typeof AuthenticatedAdminWebsiteSettingsRoute
  '/api/public/media/$id': typeof ApiPublicMediaIdRoute
  '/admin/customers/': typeof AuthenticatedAdminCustomersIndexRoute
  '/admin/enquiries/': typeof AuthenticatedAdminEnquiriesIndexRoute
  '/admin/website/': typeof AuthenticatedAdminWebsiteIndexRoute
  '/admin/website/$module/$id': typeof AuthenticatedAdminWebsiteModuleIdRoute
  '/admin/website/$module/': typeof AuthenticatedAdminWebsiteModuleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/application-submitted': typeof ApplicationSubmittedRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/coming-soon': typeof ComingSoonRoute
  '/contact': typeof ContactRoute
  '/downloads': typeof DownloadsRoute
  '/maintenance': typeof MaintenanceRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/careers/$slug': typeof CareersSlugRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/service/$slug': typeof ServiceSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/blogs': typeof BlogsIndexRoute
  '/careers': typeof CareersIndexRoute
  '/case-studies': typeof CaseStudiesIndexRoute
  '/industries': typeof IndustriesIndexRoute
  '/portfolio': typeof PortfolioIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/services': typeof ServicesIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/admin/followups': typeof AuthenticatedAdminFollowupsRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/tasks': typeof AuthenticatedAdminTasksRoute
  '/admin/team': typeof AuthenticatedAdminTeamRoute
  '/api/downloads/$name': typeof ApiDownloadsNameRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/customers/$id': typeof AuthenticatedAdminCustomersIdRoute
  '/admin/enquiries/$id': typeof AuthenticatedAdminEnquiriesIdRoute
  '/admin/website/applications': typeof AuthenticatedAdminWebsiteApplicationsRoute
  '/admin/website/financial': typeof AuthenticatedAdminWebsiteFinancialRoute
  '/admin/website/media': typeof AuthenticatedAdminWebsiteMediaRoute
  '/admin/website/settings': typeof AuthenticatedAdminWebsiteSettingsRoute
  '/api/public/media/$id': typeof ApiPublicMediaIdRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersIndexRoute
  '/admin/enquiries': typeof AuthenticatedAdminEnquiriesIndexRoute
  '/admin/website': typeof AuthenticatedAdminWebsiteIndexRoute
  '/admin/website/$module/$id': typeof AuthenticatedAdminWebsiteModuleIdRoute
  '/admin/website/$module': typeof AuthenticatedAdminWebsiteModuleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/application-submitted': typeof ApplicationSubmittedRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/coming-soon': typeof ComingSoonRoute
  '/contact': typeof ContactRoute
  '/downloads': typeof DownloadsRoute
  '/maintenance': typeof MaintenanceRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/blogs/$slug': typeof BlogsSlugRoute
  '/careers/$slug': typeof CareersSlugRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/service/$slug': typeof ServiceSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/blogs/': typeof BlogsIndexRoute
  '/careers/': typeof CareersIndexRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
  '/industries/': typeof IndustriesIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/_authenticated/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/_authenticated/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/_authenticated/admin/followups': typeof AuthenticatedAdminFollowupsRoute
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/admin/tasks': typeof AuthenticatedAdminTasksRoute
  '/_authenticated/admin/team': typeof AuthenticatedAdminTeamRoute
  '/api/downloads/$name': typeof ApiDownloadsNameRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/customers/$id': typeof AuthenticatedAdminCustomersIdRoute
  '/_authenticated/admin/enquiries/$id': typeof AuthenticatedAdminEnquiriesIdRoute
  '/_authenticated/admin/website/applications': typeof AuthenticatedAdminWebsiteApplicationsRoute
  '/_authenticated/admin/website/financial': typeof AuthenticatedAdminWebsiteFinancialRoute
  '/_authenticated/admin/website/media': typeof AuthenticatedAdminWebsiteMediaRoute
  '/_authenticated/admin/website/settings': typeof AuthenticatedAdminWebsiteSettingsRoute
  '/api/public/media/$id': typeof ApiPublicMediaIdRoute
  '/_authenticated/admin/customers/': typeof AuthenticatedAdminCustomersIndexRoute
  '/_authenticated/admin/enquiries/': typeof AuthenticatedAdminEnquiriesIndexRoute
  '/_authenticated/admin/website/': typeof AuthenticatedAdminWebsiteIndexRoute
  '/_authenticated/admin/website/$module/$id': typeof AuthenticatedAdminWebsiteModuleIdRoute
  '/_authenticated/admin/website/$module/': typeof AuthenticatedAdminWebsiteModuleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/application-submitted'
    | '/auth'
    | '/book'
    | '/coming-soon'
    | '/contact'
    | '/downloads'
    | '/maintenance'
    | '/privacy'
    | '/search'
    | '/sitemap'
    | '/sitemap.xml'
    | '/terms'
    | '/thank-you'
    | '/admin'
    | '/blogs/$slug'
    | '/careers/$slug'
    | '/case-studies/$slug'
    | '/industries/$slug'
    | '/portfolio/$slug'
    | '/resources/$slug'
    | '/service/$slug'
    | '/services/$slug'
    | '/tools/$slug'
    | '/blogs/'
    | '/careers/'
    | '/case-studies/'
    | '/industries/'
    | '/portfolio/'
    | '/resources/'
    | '/services/'
    | '/tools/'
    | '/admin/bookings'
    | '/admin/documents'
    | '/admin/followups'
    | '/admin/notifications'
    | '/admin/tasks'
    | '/admin/team'
    | '/api/downloads/$name'
    | '/admin/'
    | '/admin/customers/$id'
    | '/admin/enquiries/$id'
    | '/admin/website/applications'
    | '/admin/website/financial'
    | '/admin/website/media'
    | '/admin/website/settings'
    | '/api/public/media/$id'
    | '/admin/customers/'
    | '/admin/enquiries/'
    | '/admin/website/'
    | '/admin/website/$module/$id'
    | '/admin/website/$module/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/application-submitted'
    | '/auth'
    | '/book'
    | '/coming-soon'
    | '/contact'
    | '/downloads'
    | '/maintenance'
    | '/privacy'
    | '/search'
    | '/sitemap'
    | '/sitemap.xml'
    | '/terms'
    | '/thank-you'
    | '/blogs/$slug'
    | '/careers/$slug'
    | '/case-studies/$slug'
    | '/industries/$slug'
    | '/portfolio/$slug'
    | '/resources/$slug'
    | '/service/$slug'
    | '/services/$slug'
    | '/tools/$slug'
    | '/blogs'
    | '/careers'
    | '/case-studies'
    | '/industries'
    | '/portfolio'
    | '/resources'
    | '/services'
    | '/tools'
    | '/admin/bookings'
    | '/admin/documents'
    | '/admin/followups'
    | '/admin/notifications'
    | '/admin/tasks'
    | '/admin/team'
    | '/api/downloads/$name'
    | '/admin'
    | '/admin/customers/$id'
    | '/admin/enquiries/$id'
    | '/admin/website/applications'
    | '/admin/website/financial'
    | '/admin/website/media'
    | '/admin/website/settings'
    | '/api/public/media/$id'
    | '/admin/customers'
    | '/admin/enquiries'
    | '/admin/website'
    | '/admin/website/$module/$id'
    | '/admin/website/$module'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/application-submitted'
    | '/auth'
    | '/book'
    | '/coming-soon'
    | '/contact'
    | '/downloads'
    | '/maintenance'
    | '/privacy'
    | '/search'
    | '/sitemap'
    | '/sitemap.xml'
    | '/terms'
    | '/thank-you'
    | '/_authenticated/admin'
    | '/blogs/$slug'
    | '/careers/$slug'
    | '/case-studies/$slug'
    | '/industries/$slug'
    | '/portfolio/$slug'
    | '/resources/$slug'
    | '/service/$slug'
    | '/services/$slug'
    | '/tools/$slug'
    | '/blogs/'
    | '/careers/'
    | '/case-studies/'
    | '/industries/'
    | '/portfolio/'
    | '/resources/'
    | '/services/'
    | '/tools/'
    | '/_authenticated/admin/bookings'
    | '/_authenticated/admin/documents'
    | '/_authenticated/admin/followups'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/tasks'
    | '/_authenticated/admin/team'
    | '/api/downloads/$name'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/customers/$id'
    | '/_authenticated/admin/enquiries/$id'
    | '/_authenticated/admin/website/applications'
    | '/_authenticated/admin/website/financial'
    | '/_authenticated/admin/website/media'
    | '/_authenticated/admin/website/settings'
    | '/api/public/media/$id'
    | '/_authenticated/admin/customers/'
    | '/_authenticated/admin/enquiries/'
    | '/_authenticated/admin/website/'
    | '/_authenticated/admin/website/$module/$id'
    | '/_authenticated/admin/website/$module/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ApplicationSubmittedRoute: typeof ApplicationSubmittedRoute
  AuthRoute: typeof AuthRoute
  BookRoute: typeof BookRoute
  ComingSoonRoute: typeof ComingSoonRoute
  ContactRoute: typeof ContactRoute
  DownloadsRoute: typeof DownloadsRoute
  MaintenanceRoute: typeof MaintenanceRoute
  PrivacyRoute: typeof PrivacyRoute
  SearchRoute: typeof SearchRoute
  SitemapRoute: typeof SitemapRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ThankYouRoute: typeof ThankYouRoute
  BlogsSlugRoute: typeof BlogsSlugRoute
  CareersSlugRoute: typeof CareersSlugRoute
  CaseStudiesSlugRoute: typeof CaseStudiesSlugRoute
  IndustriesSlugRoute: typeof IndustriesSlugRoute
  PortfolioSlugRoute: typeof PortfolioSlugRoute
  ResourcesSlugRoute: typeof ResourcesSlugRoute
  ServiceSlugRoute: typeof ServiceSlugRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  ToolsSlugRoute: typeof ToolsSlugRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
  CareersIndexRoute: typeof CareersIndexRoute
  CaseStudiesIndexRoute: typeof CaseStudiesIndexRoute
  IndustriesIndexRoute: typeof IndustriesIndexRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
  ApiDownloadsNameRoute: typeof ApiDownloadsNameRoute
  ApiPublicMediaIdRoute: typeof ApiPublicMediaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/application-submitted': {
      id: '/application-submitted'
      path: '/application-submitted'
      fullPath: '/application-submitted'
      preLoaderRoute: typeof ApplicationSubmittedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coming-soon': {
      id: '/coming-soon'
      path: '/coming-soon'
      fullPath: '/coming-soon'
      preLoaderRoute: typeof ComingSoonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/blogs'
      fullPath: '/blogs/'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/$slug': {
      id: '/blogs/$slug'
      path: '/blogs/$slug'
      fullPath: '/blogs/$slug'
      preLoaderRoute: typeof BlogsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/': {
      id: '/careers/'
      path: '/careers'
      fullPath: '/careers/'
      preLoaderRoute: typeof CareersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/$slug': {
      id: '/careers/$slug'
      path: '/careers/$slug'
      fullPath: '/careers/$slug'
      preLoaderRoute: typeof CareersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/': {
      id: '/case-studies/'
      path: '/case-studies'
      fullPath: '/case-studies/'
      preLoaderRoute: typeof CaseStudiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/$slug': {
      id: '/case-studies/$slug'
      path: '/case-studies/$slug'
      fullPath: '/case-studies/$slug'
      preLoaderRoute: typeof CaseStudiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/': {
      id: '/industries/'
      path: '/industries'
      fullPath: '/industries/'
      preLoaderRoute: typeof IndustriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/$slug': {
      id: '/industries/$slug'
      path: '/industries/$slug'
      fullPath: '/industries/$slug'
      preLoaderRoute: typeof IndustriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/portfolio'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof PortfolioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/$slug': {
      id: '/portfolio/$slug'
      path: '/portfolio/$slug'
      fullPath: '/portfolio/$slug'
      preLoaderRoute: typeof PortfolioSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$slug': {
      id: '/resources/$slug'
      path: '/resources/$slug'
      fullPath: '/resources/$slug'
      preLoaderRoute: typeof ResourcesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/$slug': {
      id: '/service/$slug'
      path: '/service/$slug'
      fullPath: '/service/$slug'
      preLoaderRoute: typeof ServiceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/$slug': {
      id: '/tools/$slug'
      path: '/tools/$slug'
      fullPath: '/tools/$slug'
      preLoaderRoute: typeof ToolsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/bookings': {
      id: '/_authenticated/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AuthenticatedAdminBookingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/documents': {
      id: '/_authenticated/admin/documents'
      path: '/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AuthenticatedAdminDocumentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/followups': {
      id: '/_authenticated/admin/followups'
      path: '/followups'
      fullPath: '/admin/followups'
      preLoaderRoute: typeof AuthenticatedAdminFollowupsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/tasks': {
      id: '/_authenticated/admin/tasks'
      path: '/tasks'
      fullPath: '/admin/tasks'
      preLoaderRoute: typeof AuthenticatedAdminTasksRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/team': {
      id: '/_authenticated/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AuthenticatedAdminTeamRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/downloads/$name': {
      id: '/api/downloads/$name'
      path: '/api/downloads/$name'
      fullPath: '/api/downloads/$name'
      preLoaderRoute: typeof ApiDownloadsNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/customers/': {
      id: '/_authenticated/admin/customers/'
      path: '/customers'
      fullPath: '/admin/customers/'
      preLoaderRoute: typeof AuthenticatedAdminCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/customers/$id': {
      id: '/_authenticated/admin/customers/$id'
      path: '/customers/$id'
      fullPath: '/admin/customers/$id'
      preLoaderRoute: typeof AuthenticatedAdminCustomersIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/enquiries/': {
      id: '/_authenticated/admin/enquiries/'
      path: '/enquiries'
      fullPath: '/admin/enquiries/'
      preLoaderRoute: typeof AuthenticatedAdminEnquiriesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/enquiries/$id': {
      id: '/_authenticated/admin/enquiries/$id'
      path: '/enquiries/$id'
      fullPath: '/admin/enquiries/$id'
      preLoaderRoute: typeof AuthenticatedAdminEnquiriesIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/website/': {
      id: '/_authenticated/admin/website/'
      path: '/website'
      fullPath: '/admin/website/'
      preLoaderRoute: typeof AuthenticatedAdminWebsiteIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/website/applications': {
      id: '/_authenticated/admin/website/applications'
      path: '/website/applications'
      fullPath: '/admin/website/applications'
      preLoaderRoute: typeof AuthenticatedAdminWebsiteApplicationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/website/financial': {
      id: '/_authenticated/admin/website/financial'
      path: '/website/financial'
      fullPath: '/admin/website/financial'
      preLoaderRoute: typeof AuthenticatedAdminWebsiteFinancialRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/website/media': {
      id: '/_authenticated/admin/website/media'
      path: '/website/media'
      fullPath: '/admin/website/media'
      preLoaderRoute: typeof AuthenticatedAdminWebsiteMediaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/website/settings': {
      id: '/_authenticated/admin/website/settings'
      path: '/website/settings'
      fullPath: '/admin/website/settings'
      preLoaderRoute: typeof AuthenticatedAdminWebsiteSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/media/$id': {
      id: '/api/public/media/$id'
      path: '/api/public/media/$id'
      fullPath: '/api/public/media/$id'
      preLoaderRoute: typeof ApiPublicMediaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/website/$module/': {
      id: '/_authenticated/admin/website/$module/'
      path: '/website/$module'
      fullPath: '/admin/website/$module/'
      preLoaderRoute: typeof AuthenticatedAdminWebsiteModuleIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/website/$module/$id': {
      id: '/_authenticated/admin/website/$module/$id'
      path: '/website/$module/$id'
      fullPath: '/admin/website/$module/$id'
      preLoaderRoute: typeof AuthenticatedAdminWebsiteModuleIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminBookingsRoute: typeof AuthenticatedAdminBookingsRoute
  AuthenticatedAdminDocumentsRoute: typeof AuthenticatedAdminDocumentsRoute
  AuthenticatedAdminFollowupsRoute: typeof AuthenticatedAdminFollowupsRoute
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminTasksRoute: typeof AuthenticatedAdminTasksRoute
  AuthenticatedAdminTeamRoute: typeof AuthenticatedAdminTeamRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminCustomersIdRoute: typeof AuthenticatedAdminCustomersIdRoute
  AuthenticatedAdminEnquiriesIdRoute: typeof AuthenticatedAdminEnquiriesIdRoute
  AuthenticatedAdminWebsiteApplicationsRoute: typeof AuthenticatedAdminWebsiteApplicationsRoute
  AuthenticatedAdminWebsiteFinancialRoute: typeof AuthenticatedAdminWebsiteFinancialRoute
  AuthenticatedAdminWebsiteMediaRoute: typeof AuthenticatedAdminWebsiteMediaRoute
  AuthenticatedAdminWebsiteSettingsRoute: typeof AuthenticatedAdminWebsiteSettingsRoute
  AuthenticatedAdminCustomersIndexRoute: typeof AuthenticatedAdminCustomersIndexRoute
  AuthenticatedAdminEnquiriesIndexRoute: typeof AuthenticatedAdminEnquiriesIndexRoute
  AuthenticatedAdminWebsiteIndexRoute: typeof AuthenticatedAdminWebsiteIndexRoute
  AuthenticatedAdminWebsiteModuleIdRoute: typeof AuthenticatedAdminWebsiteModuleIdRoute
  AuthenticatedAdminWebsiteModuleIndexRoute: typeof AuthenticatedAdminWebsiteModuleIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminBookingsRoute: AuthenticatedAdminBookingsRoute,
  AuthenticatedAdminDocumentsRoute: AuthenticatedAdminDocumentsRoute,
  AuthenticatedAdminFollowupsRoute: AuthenticatedAdminFollowupsRoute,
  AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
  AuthenticatedAdminTasksRoute: AuthenticatedAdminTasksRoute,
  AuthenticatedAdminTeamRoute: AuthenticatedAdminTeamRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminCustomersIdRoute: AuthenticatedAdminCustomersIdRoute,
  AuthenticatedAdminEnquiriesIdRoute: AuthenticatedAdminEnquiriesIdRoute,
  AuthenticatedAdminWebsiteApplicationsRoute:
    AuthenticatedAdminWebsiteApplicationsRoute,
  AuthenticatedAdminWebsiteFinancialRoute:
    AuthenticatedAdminWebsiteFinancialRoute,
  AuthenticatedAdminWebsiteMediaRoute: AuthenticatedAdminWebsiteMediaRoute,
  AuthenticatedAdminWebsiteSettingsRoute:
    AuthenticatedAdminWebsiteSettingsRoute,
  AuthenticatedAdminCustomersIndexRoute: AuthenticatedAdminCustomersIndexRoute,
  AuthenticatedAdminEnquiriesIndexRoute: AuthenticatedAdminEnquiriesIndexRoute,
  AuthenticatedAdminWebsiteIndexRoute: AuthenticatedAdminWebsiteIndexRoute,
  AuthenticatedAdminWebsiteModuleIdRoute:
    AuthenticatedAdminWebsiteModuleIdRoute,
  AuthenticatedAdminWebsiteModuleIndexRoute:
    AuthenticatedAdminWebsiteModuleIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ApplicationSubmittedRoute: ApplicationSubmittedRoute,
  AuthRoute: AuthRoute,
  BookRoute: BookRoute,
  ComingSoonRoute: ComingSoonRoute,
  ContactRoute: ContactRoute,
  DownloadsRoute: DownloadsRoute,
  MaintenanceRoute: MaintenanceRoute,
  PrivacyRoute: PrivacyRoute,
  SearchRoute: SearchRoute,
  SitemapRoute: SitemapRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ThankYouRoute: ThankYouRoute,
  BlogsSlugRoute: BlogsSlugRoute,
  CareersSlugRoute: CareersSlugRoute,
  CaseStudiesSlugRoute: CaseStudiesSlugRoute,
  IndustriesSlugRoute: IndustriesSlugRoute,
  PortfolioSlugRoute: PortfolioSlugRoute,
  ResourcesSlugRoute: ResourcesSlugRoute,
  ServiceSlugRoute: ServiceSlugRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  ToolsSlugRoute: ToolsSlugRoute,
  BlogsIndexRoute: BlogsIndexRoute,
  CareersIndexRoute: CareersIndexRoute,
  CaseStudiesIndexRoute: CaseStudiesIndexRoute,
  IndustriesIndexRoute: IndustriesIndexRoute,
  PortfolioIndexRoute: PortfolioIndexRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  ToolsIndexRoute: ToolsIndexRoute,
  ApiDownloadsNameRoute: ApiDownloadsNameRoute,
  ApiPublicMediaIdRoute: ApiPublicMediaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
